In [1]:
from random import random

from statsmodels.tsa.arima.model import ARIMA

In [2]:
n_observations = 20

data = [random() for _ in range(n_observations)]
data

[0.469641798093444,
 0.5696740090867146,
 0.8816118419446952,
 0.8814249844130165,
 0.7106867611994668,
 0.4851682361387444,
 0.8982937741659162,
 0.5590897621376834,
 0.5176731161974892,
 0.5820576799855757,
 0.22348617839156337,
 0.4142964105618503,
 0.07490298053764832,
 0.6883595645766262,
 0.5644619617443556,
 0.18835875552991332,
 0.11637809241962949,
 0.5843992797364032,
 0.4222674276597479,
 0.39935299437427396]

In [3]:
model = ARIMA(data)
model_fit = model.fit()
data_prediction = model_fit.predict(n_observations, 10 + n_observations)
data_prediction

array([0.51157438, 0.51157438, 0.51157438, 0.51157438, 0.51157438,
       0.51157438, 0.51157438, 0.51157438, 0.51157438, 0.51157438,
       0.51157438])

In [4]:
model = ARIMA(data, order=(0, 0, 3))
model_fit = model.fit()
data_prediction = model_fit.predict(n_observations, 10 + n_observations)
data_prediction

array([0.51037981, 0.49909024, 0.50318694, 0.51042091, 0.51042091,
       0.51042091, 0.51042091, 0.51042091, 0.51042091, 0.51042091,
       0.51042091])

In [5]:
model = ARIMA(data, order=(0, 0, 1))
model_fit = model.fit()
data_prediction = model_fit.predict(n_observations, 10 + n_observations)
data_prediction

array([0.49076708, 0.51015372, 0.51015372, 0.51015372, 0.51015372,
       0.51015372, 0.51015372, 0.51015372, 0.51015372, 0.51015372,
       0.51015372])

In [6]:
model = ARIMA(data, order=(3, 0, 1))
model_fit = model.fit()
data_prediction = model_fit.predict(n_observations, 10 + n_observations)
data_prediction

/home/green-machine/anaconda3/lib/python3.9/site-packages/statsmodels/base/model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


array([0.46526824, 0.47721452, 0.4757671 , 0.48527042, 0.49317718,
       0.49703576, 0.5004238 , 0.50354773, 0.50585486, 0.5076055 ,
       0.50903286])

In [7]:
n_observations = 200

data = [random() for _ in range(n_observations)]
data

[0.45117783140289525,
 0.18625204773060056,
 0.6064921405001448,
 0.5077958478729918,
 0.9189421608120963,
 0.04581785952473105,
 0.3392255469129458,
 0.18519480570436786,
 0.18888622272702604,
 0.10205006028120112,
 0.02769333023308873,
 0.0197733941224828,
 0.04976556720145031,
 0.6239806432816829,
 0.10549285192866609,
 0.14670418599621438,
 0.32902905941535643,
 0.4020993154046588,
 0.9446276749787035,
 0.00533117265267069,
 0.8057125423605883,
 0.1217008477627699,
 0.5000490555083583,
 0.13750185528862324,
 0.5138790104530965,
 0.32517386290514416,
 0.5739421270370375,
 0.6336025456193781,
 0.5968790451757682,
 0.8589386296771478,
 0.8011398216984409,
 0.5461554357757552,
 0.9222571126235963,
 0.37332719431413675,
 0.5467223286680385,
 0.949049068777301,
 0.031622800162796616,
 0.2682414332457055,
 0.9268122185959163,
 0.37251684705566857,
 0.14340195579985437,
 0.8535362089715348,
 0.010808114497693588,
 0.44805131598441195,
 0.4926212167513614,
 0.3496542465237398,
 0.6574854728

In [8]:
model = ARIMA(data, order=(3, 0, 1))
model_fit = model.fit()
data_prediction = model_fit.predict(n_observations, 10 + n_observations)
data_prediction

array([0.44575243, 0.46597583, 0.48030606, 0.46852842, 0.47378078,
       0.47285182, 0.47251987, 0.47293593, 0.47274501, 0.47279214,
       0.47280006])

In [9]:
n_observations = 20

data = [_ + random() for _ in range(n_observations)]
data

[0.6076888862300066,
 1.34800386651257,
 2.3449938286147685,
 3.8827424076735024,
 4.403469638702875,
 5.57046103654826,
 6.221986311013035,
 7.916855109360206,
 8.322464643003707,
 9.977785950680131,
 10.204202989102107,
 11.052736756604734,
 12.972439867174176,
 13.71823394783806,
 14.274442585841319,
 15.55851483497202,
 16.242405992577307,
 17.251961838815397,
 18.30320489723926,
 19.138996340319355]

In [10]:
model = ARIMA(data, order=(1, 1, 1))
model_fit = model.fit()
data_prediction = model_fit.predict(n_observations, 10 + n_observations)
data_prediction

/home/green-machine/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/home/green-machine/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'


array([20.10237592, 21.06574586, 22.02910618, 22.99245685, 23.9557979 ,
       24.91912931, 25.88245109, 26.84576323, 27.80906574, 28.77235862,
       29.73564186])

In [11]:
from statsmodels.tsa.statespace.sarimax import SARIMAX

In [12]:
n_observations = 20

data = [_ + random() for _ in range(n_observations)]
data

[0.050960298943826365,
 1.6630352399022932,
 2.055663746371556,
 3.708918110657078,
 4.252683760115337,
 5.336988643318273,
 6.6647785816341765,
 7.4654393591868,
 8.078374442288384,
 9.178713099189745,
 10.541372754287812,
 11.58981655401238,
 12.255754614121148,
 13.402299159743277,
 14.739151092271438,
 15.573025592792455,
 16.221524536503605,
 17.9500732558358,
 18.774306849820192,
 19.912853850735544]

In [13]:
model = SARIMAX(data, order=(1, 1, 1), seasonal_order=(0, 0, 0, 0))
model_fit = model.fit()

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.00493D+02    |proj g|=  5.62989D+02

At iterate    5    f=  1.73750D+00    |proj g|=  6.82471D-01

At iterate   10    f=  8.66777D-01    |proj g|=  4.07202D-01

At iterate   15    f=  7.54173D-01    |proj g|=  2.09521D-01

At iterate   20    f=  6.34377D-01    |proj g|=  3.65020D-02

At iterate   25    f=  5.95566D-01    |proj g|=  5.50751D-02

At iterate   30    f=  5.83874D-01    |proj g|=  1.75362D-03

At iterate   35    f=  5.81574D-01    |proj g|=  1.82370D-02

At iterate   40    f=  5.81192D-01    |proj g|=  3.88230D-03

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg 

 This problem is unconstrained.

   evaluations in the last line search.  Termination
   may possibly be caused by a bad search direction.


In [14]:
data_prediction = model_fit.predict(n_observations, 10 + n_observations)
data_prediction

array([20.95052677, 21.9881886 , 23.02583932, 24.06347894, 25.10110747,
       26.1387249 , 27.17633123, 28.21392646, 29.25151059, 30.28908362,
       31.32664556])

In [16]:
data = [_ + 3 * _ % 6 + random() for _ in range(n_observations)]
data

[0.11017026232592841,
 4.3413954640202315,
 2.045920414512903,
 6.453254971442544,
 4.847469845976997,
 8.007627893079402,
 6.472194466364989,
 10.909082696699059,
 8.035029229332762,
 12.358521390103204,
 10.37056923696528,
 14.321090312691018,
 12.790814038562532,
 16.25402205805407,
 14.107065246251372,
 18.956263774779046,
 16.49022839335284,
 20.759127336037352,
 18.00463013670481,
 22.78907372569034]

In [21]:
model = SARIMAX(data, order=(1, 1, 1), seasonal_order=(6, 6, 6, 6))
model_fit = model.fit()

/home/green-machine/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
/home/green-machine/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for seasonal ARMA. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'


RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           15     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f= -0.00000D+00    |proj g|=  0.00000D+00

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   15      0      1      0     0     0   0.000D+00  -0.000D+00
  F =  -0.0000000000000000     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            


 This problem is unconstrained.


In [22]:
import numpy as np

In [25]:
data1 = [_ + random() for _ in range(n_observations)]
data2 = [_ + random() for _ in range(n_observations, 20 + n_observations)]
data1

[0.39070093525011573,
 1.8506189636096844,
 2.1140837915022757,
 3.1074290857054327,
 4.94162103388196,
 5.499087874165172,
 6.664717274459209,
 7.095166143345173,
 8.939124915841496,
 9.100570143224475,
 10.04359302357881,
 11.369063881036153,
 12.869107772729656,
 13.285934745936723,
 14.022146100729088,
 15.475470624437296,
 16.714470804955354,
 17.992563156681857,
 18.477546023806415,
 19.196553682633215]

In [26]:
data2

[20.430167064220765,
 21.972794154480756,
 22.856588430958634,
 23.387589639048013,
 24.245817100219462,
 25.214754877450194,
 26.00140876702679,
 27.3641304292822,
 28.945477407880094,
 29.858334486837094,
 30.406661362631965,
 31.763059221513725,
 32.50486335134529,
 33.208255466724204,
 34.62873568681229,
 35.73485916367702,
 36.52969608488716,
 37.66587132226137,
 38.170901681164025,
 39.16750102007813]

In [28]:
model = SARIMAX(data1, exog=data2, order=(0, 0, 0,), seasonal_order=(1, 1, 1, 2))

In [29]:
model_fit = model.fit()

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            4     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  7.30861D-01    |proj g|=  1.11601D+00

At iterate    5    f=  7.03837D-01    |proj g|=  2.31784D-01

At iterate   10    f=  6.11162D-01    |proj g|=  1.09567D-01

At iterate   15    f=  6.08680D-01    |proj g|=  2.36604D-02

At iterate   20    f=  6.07886D-01    |proj g|=  5.91453D-02

At iterate   25    f=  6.07758D-01    |proj g|=  2.73129D-03

At iterate   30    f=  6.07747D-01    |proj g|=  7.10275D-03

At iterate   35    f=  6.07741D-01    |proj g|=  2.50627D-02

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function 

 This problem is unconstrained.

   evaluations in the last line search.  Termination
   may possibly be caused by a bad search direction.


In [40]:
exog2 = np.array(
    [_ + random() for _ in range(20 + n_observations, 30 + n_observations)]
).reshape((10, 1))
exog2

array([[40.17365419],
       [41.59602842],
       [42.74630511],
       [43.05032923],
       [44.83984253],
       [45.21405909],
       [46.57743473],
       [47.67959728],
       [48.39619534],
       [49.39933128]])

In [42]:
data_prediction = model_fit.predict(n_observations, 9 + n_observations, exog=exog2)
data_prediction

array([20.28990404, 21.53569841, 22.88750907, 23.00382928, 24.99596919,
       25.18308359, 26.74611762, 27.66643278, 28.57801435, 29.39858776])